version: "3.7"

services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    command: |
      tail -f /dev/null

  database:
    extends:
      file: docker-compose.base.yml
      service: database

  nginx_proxy:
    extends:
      file: docker-compose.base.yml
      service: nginx_proxy

volumes:
  database:
  static_files:
  media_files:
