# Generated by Django 4.1.7 on 2023-11-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(editable=False)),
                ('record', models.PositiveIntegerField()),
                ('ws_10m_avg', models.FloatField()),
                ('ws_10m_max', models.FloatField()),
            ],
        ),
    ]
