# Generated by Django 4.1.7 on 2023-11-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='data',
            name='record',
            field=models.BigIntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(editable=False, unique=True),
        ),
    ]
